# Site settings
title: Mike Whitby
email: m.whitby@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a PHP developer who specialises in Magento, I live in Nottingham but
  work as a contractor in London.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mikewhitby.co.uk" # the base hostname & protocol for your site
twitter_username: mikewhitby
github_username:  mikewhitby

# Build settings
markdown: kramdown
